[workspace]

members = [
  "assembly-line",
  "gigasecond",
  "health-statistics",
  "hello-world",
  "leap",
  "low-power-embedded-game",
  "lucians-luscious-lasagna",
  "magazine-cutout",
  "resistor-color",
  "reverse-string",
  "rpn-calculator",
  "role-playing-game",
  "semi-structured-logs",
  "short-fibonacci",
]
