[workspace]

members = [
  "allergies",
  "anagram",
  "assembly-line",
  "clock",
  "gigasecond",
  "health-statistics",
  "hello-world",
  "leap",
  "low-power-embedded-game",
  "lucians-luscious-lasagna",
  "luhn",
  "magazine-cutout",
  "minesweeper",
  "palindrome-products",
  "resistor-color",
  "reverse-string",
  "rna-transcription",
  "role-playing-game",
  "rpn-calculator",
  "semi-structured-logs",
  "short-fibonacci",
  "space-age",
  "sublist",
  "tournament",
]
