[workspace]

members = [
  "assembly-line/",
  "health-statistics",
  "hello-world/",
  "leap/",
  "low-power-embedded-game/",
  "lucians-luscious-lasagna/",
  "resistor-color",
  "role-playing-game",
  "semi-structured-logs/",
  "short-fibonacci/",
]
