lint:
    cargo fmt
    cargo clippy --fix --allow-dirty

# Tip use this in VSCode terminal to get instant feedback on tests.
# watch:
#  cargo watch --clear --shell "cargo test --test isogram --quiet"
